### ISSUE TITLE
node getTopics validate query

### ISSUE THREAD

**Issue by romilrobtsenkov** [romilrobtsenkov/teemaderegister-react#49]

**Comment by priiti** [comment]
Kas saaksid kommenteerida, mis nõudmised on valideerimisel?

**Comment by romilrobtsenkov** [comment]
Süvenesin ja mõtlesin natuke. 
curriculumId, supervisorId osas võiks kontrollida, et tegu on mongoose'ile sobivate id'dega. Minu teada on olemas fn mille vastu kontrollida.

columnKey osas võiksid olla lubatud need väljad, millel sort küljes kui vaadata tabeleid
types lubatud BA SE, need võib isegi konstantide osas defineerida vt https://github.com/romilrobtsenkov/teemaderegister-be/pull/24. Ja schema osas ka kasutusele võtta.

sub'i võiks ka kontrollida, et lubatud kolme seas.

Kui vähegi võimaliks siis errorit pole vaja anda, vaid default väärtusele üle viia.

ega vist rohkem polegi. Sama tegelikult laieneks getSupervisors'ile. sub'i pole vaja kontrollida, sest ainult 2 valikut.

**Comment by priiti** [comment]
Hästi. Kas võiksid veel öelda, mis default väärtused olla võiksid. Näiteks topic types osas ja sub osas, lisaks supervisors osas. Btw, mis see sub on? 🤔 
Kui ObjectId ära kontrollin, kas soovid selle osas samuti mõnda default väärtust nii CurriculumId kui ka SupervisorId juures?

**Comment by romilrobtsenkov** [comment]
tabeli sisus – tab (topics,supervisors) ja alamvalik sub (topics puhul: available,registered,defended supervisor'i puhul: supervised,all)

default väärtused enam-vähem olemas seal. Sordi puhul nt
`let sortKey = columnKey || defaultSort`
Aga columnkey kontroll oleks vaja eelnevalt teha, et kui kaasas, et siis kontrollida et lubatud väärtuste seas aga seda tuleb tulpade osas vaadata, et mis kaasa saadetakse. Vaatasin, et tegelikult sul täiendavalt default väärtuste seadmist teha vist ei tulegi ühegi väärtuse puhul.

kui saadetud id'd ei ole id'd siis vaikeväärtust ei ole, pigem saadaks bad request tagasi.
