### ISSUE TITLE
Admin dashboard

### ISSUE THREAD

**Issue by romilrobtsenkov** [romilrobtsenkov/teemaderegister-react#76]
User has dashboard after login with separate sub-pages that are in side menu (is dependant on roles, can be added later)
- Topics (later added that supervisor can see his/her topics)
- Confirmation (topics that are in the middle of confirmation process, seen by admin, supervisor... others)
- Users (admin can see users and modify them)

Current issue should provide a dashboard with side menu and empty pages and is only front-end based.

See ant.design admin dashboard examples

**Comment by hinrek** [comment]
Issue #32 needs Admin dashboard asap.

**Comment by romilrobtsenkov** [comment]
Tegelikult on nii, et neil midagi juba on. Saate äkki pushida. Samas mõtlen, et #32 puhul @hinrek on nii, et neid oleks hea saata siis sama päringuga admin poolel, mis muidu õppejõu topics'id, lihtsalt reacti poolel siis eraldi jupina välja näidata.
